[package]
name = "my_project"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
surrealdb = "2.0.4"
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"] }
